#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import sys
import copy

def tri_selection(tab, nb_elem):
    etape = 0
    i = 0
    while i < (nb_elem - 1):
        min = i
        j = i + 1
        while j < nb_elem:
            etape = etape + 1
            if tab[j] < tab[min]:
                min = j
            j = j + 1
        if min != i:
            tmp = tab[i]
            tab[i] = tab[min]
            tab[min] = tmp
        i = i + 1
    print "tri par sélection :",etape,"comparaisons"
    return etape

def tri_insertion_old(tab, nb_elem):
    etape = 0
    i = 0
    while i < nb_elem:
        x = tab[i]
        j = i
        while j > 0 and tab[j - 1] > x:
            etape = etape + 1
            tab[j] = tab[j - 1]
            j = j - 1
        tab[j] = x
        i = i + 1
    print "tri par insertion :",etape,"comparaisons"
    return etape

def tri_insertion(tab):
    n = 0
    i = 0
    new_tab = []
    while i < len(tab):
        if new_tab == []:
            new_tab.append(tab[i])
        else:
            c = 0
            while c < len(new_tab):
                n = n + 1
                if (new_tab[c] > tab[i]):
                    new_tab.insert(c, tab[i])
                    break
                c = c + 1
            if c == len(new_tab):
                new_tab.append(tab[i])
        i = i + 1
    print "tri par insertion :",n,"comparaisons"

def tri_bulle(tab, nb_elem):
    etape = 0
    i = nb_elem
    while i > 0:
        j = 0
        while j < (i - 1):
            if tab[j + 1] < tab[j]:
                tmp = tab[j + 1]
                tab[j + 1] = tab[j]
                tab[j] = tmp
            j = j + 1
            etape = etape + 1
        i = i - 1
    print "tri à bulles :",etape,"comparaisons"
    return etape

def partition(tab, left, right, etape):
    pivot = tab[right]
    i = left
    j = left
    while j < right:
        if tab[j] <= pivot:
            etape[0] = etape[0] + 1
            tab[i], tab[j] = tab[j], tab[i]
            i = i + 1
        j = j + 1
    tab[i], tab[right] = tab[right], tab[i]
    return i

def tri_rapide_old(tab, left, right, etape):
    if left < right:
        etape[0] = etape[0] + 1
        part = partition(tab, left, right, etape)
        tri_rapide(tab, left, part - 1, etape)
        tri_rapide(tab, part + 1, right, etape)
    return etape

def tri_rapide(tab):
    if (len(tab) < 2):
        return 0
    etape = 0
    pivot = 0
    left = []
    right = []
    i = 0
    while i < len(tab):
        if i != pivot:
            etape = etape + 1
            if tab[i] < tab[pivot]:
                left.append(tab[i])
            if tab[i] >= tab[pivot]:
                right.append(tab[i])
        i = i + 1
    etape = etape + tri_rapide(left)
    etape = etape + tri_rapide(right)
    return etape

def fusion(a, b, etape):
    if a == []:
        return b
    if b == []:
        return a
    etape[0] = etape[0] + 1
    if a[0] < b[0]:
        return ([a[0]] + fusion(a[1:], b, etape))
    else:
        return ([b[0]] + fusion(a, b[1:], etape))


def tri_fusion(tab, etape):
    if len(tab) <= 1:
        return tab
    else:
        return fusion(tri_fusion(tab[0:len(tab)//2], etape), tri_fusion(tab[len(tab)//2:], etape), etape)


## main

if len(sys.argv) <= 1:
    exit(1)
with open(sys.argv[1]) as content_file:
    try:
        content = [float(n) for n in content_file.read().split()]
    except:
        exit(1)

l = len(content)
print l,"éléments"
tri_selection(copy.deepcopy(content), l)
tri_insertion(copy.deepcopy(content))
tri_bulle(copy.deepcopy(content), l)

etape = [0]
tri_fusion(copy.deepcopy(content), etape)
print "tri fusion :",etape[0],"comparaisons"

#print "tri rapide :",tri_rapide(copy.deepcopy(content), 0, l - 1, etape = [0])[0],"comparaisons"
print "tri rapide :",tri_rapide(copy.deepcopy(content)),"comparaisons"

exit(0)